version: "3.9"

services:
    nginx:
        container_name: nginx
        build: docker/nginx
        restart: unless-stopped
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - app
        ports:
            - "8080:80"

    app:
        container_name: app
        build: docker/app
        restart: unless-stopped
        tty: true
        working_dir: /app
        volumes:
            - .:/app

networks:
    default:
        driver: bridge
